version: "3"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    restart: always
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

  snmp:
    image: quay.io/prometheus/snmp-exporter
    volumes:
      - /opt/docker-persist/snmp-exporter:/etc/snmp_exporter
    ports:
      - 9116:9116
      - 116:116/udp
    restart: always
    command: --config.file=/etc/snmp_exporter/snmp.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  prometheus-data:
  grafana-storage:
