version: '3'
services:
  cortana:
    build:
      context: .
      dockerfile: Cortana_V3.yml
    image: cortana_v3
  cortana:
    build:
      context: .
      dockerfile: Prometheus_v3.yml
    image: Prometheus_v3
