version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_EDU
    ports:
      - "9090:9090"
    volumes:
      - /path/to/prometheus.yml:/etc/prometheus/prometheus.yml
      - /path/to/rules:/etc/prometheus/rules
      - /path/to/alerts:/etc/prometheus/alerts
