version: '1.0'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_EDU
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    networks:
      - prometheus-network

volumes:
  prometheus_data:

networks:
  prometheus-network:
